### ISSUE TITLE
update the dbs

### ISSUE THREAD

**Issue by NikZak** [efdevcon/monorepo#4]
Is there a plan to run `bun run github`, `bun run gitcoin`, etc on the server in order to update the website databases to latest values? Or how often is it generally run?

**Comment by wslyvh** [comment]
Hi, if you're talking about the discount databases, then no. We took 1 snapshot prior to the launch to reward activate contributions/participations retroactively. They will not get updated for this year.

But make sure to check out all the ticket options on the website.
Since you're here on Github, you could likely apply for a builder discount manually
https://devcon.org/en/tickets/

Will close this issue, but let me know if you have other questions
